apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: {{ include "gophprofile.databaseDSN" . | quote }}
  RABBITMQ_URL: {{ include "gophprofile.rabbitmqURL" . | quote }}
  S3_ACCESS_KEY: {{ include "gophprofile.s3AccessKey" . | quote }}
  S3_SECRET_KEY: {{ include "gophprofile.s3SecretKey" . | quote }}
