{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.rabbitmqHost" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  selector:
    {{- include "gophprofile.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: prometheus
      port: 15692
      targetPort: prometheus
{{- end }}
